EasyTier/EasyTier

easytier-core/Cargo.toml, easytier-core/build.rs, easytier-core/src/main.rs, easytier-core/src/peer_center/instance.rs, easytier-core/src/peer_center/mod.rs, easytier-core/src/peer_center/server.rs, easytier-core/src/peer_center/service.rs, easytier-core/src/peers/peer_manager.rs, easytier-core/src/peers/peer_map.rs, easytier-core/src/peers/rpc_service.rs, easytier-core/src/tests/mod.rs, easytier-core/src/tunnels/stats.rs
peer_center is used to collect peer info into one peer node.
the center node is selected with the following rules:
1. has smallest peer id
2. TODO: has allow_to_be_center peer feature
peer center is not guaranteed to be stable and can be changed when peer enter
or leave.  it's used to reduce the cost to exchange infos between peers.
=> introduce peer center

.github/workflows/rust.yml, Cargo.lock, easytier/Cargo.toml, easytier/src/tunnel/wireguard.rs
issues: https://github.com/KKRainbow/EasyTier/issues/74
=> 🐞 fix: 修复nightly错误 (https://github.com/KKRainbow/EasyTier/issues/74)

easytier/build.rs
fix unable to correctly find `protoc` path from `PATH`
just missing the suffix for executable files under Windows
merely converting `protoc` into `protoc.exe`
=> 🐞 fix: Unable to correctly locate `protoc` in `PATH`

.github/workflows/core.yml, .github/workflows/gui.yml, .github/workflows/test.yml
根据修改的文件路径，触发 GUI 或 Core 的构建以减少构建时间
由单一一个 workflow 拆分成三处，触发路径分别为：
````
EasyTier Test：
- easytier.toml
- easytier/**
- easytier-gui/**
- .github/workflows/test.yml
EasyTier Core：
- easytier.toml
- easytier/**
- .github/workflows/core.yml
EasyTier GUI：
- easytier.toml
- easytier-gui/**
- .github/workflows/gui.yml
````
疑问：
1. GUI 使用了 Core，每次构建时是否能够使用 workflow  EasyTier Core 中生成的缓存，否则还需重新构建 Core（并不能减少构建时间）
2. Core 发生变化是否需要重新构建 GUI （无法得知 Core 变化是否影响 GUI）
3. 发布版本时修改 EasyTier 版本以及 tauri.config.json 版本号进行同时构建？
=> 🐎 ci: modify action on paths and split the steps

.github/workflows/core.yml
- **only upx on linux**
upx with --lzma or --best failed to run on win10 & win7
upx -9 on win 10 will be isolated by win defender
=> only upx on linux

easytier/src/gateway/icmp_proxy.rs, easytier/src/gateway/ip_reassembler.rs, easytier/src/gateway/mod.rs, easytier/src/gateway/udp_proxy.rs, easytier/src/instance/virtual_nic.rs, easytier/src/tests/three_node.rs, easytier/src/tunnel/common.rs, easytier/src/tunnel/udp.rs
icmp/udp proxy do not rely on kernel net stack, but currently not handle ip fragmentation correctly.
this patch add ip resembler to merge fragmented ip packet for udp/icmp proxy
=> correctly handle ip fragment for udp/icmp proxy

Cargo.lock, easytier/Cargo.toml, easytier/src/common/config.rs, easytier/src/common/global_ctx.rs, easytier/src/connector/mod.rs, easytier/src/easytier-core.rs, easytier/src/gateway/icmp_proxy.rs, easytier/src/gateway/mod.rs, easytier/src/gateway/tcp_proxy.rs, easytier/src/gateway/tokio_smoltcp/channel_device.rs, easytier/src/gateway/tokio_smoltcp/device.rs, easytier/src/gateway/tokio_smoltcp/mod.rs, easytier/src/gateway/tokio_smoltcp/reactor.rs, easytier/src/gateway/tokio_smoltcp/socket.rs, easytier/src/gateway/tokio_smoltcp/socket_allocator.rs, easytier/src/gateway/udp_proxy.rs, easytier/src/instance/instance.rs, easytier/src/peers/peer_manager.rs, easytier/src/peers/peer_ospf_route.rs, easytier/src/tests/three_node.rs, easytier/src/tunnel/wireguard.rs
no tun mode can be enabled by arg --no-tun, no-tun mode do not need root permission.
when using no tun mode, other virtual node can visit this node but not reverse.
no-tun node may use SOCKS5 to visit other node, but not in this patch.
=> support no tun mode

easytier/src/common/config.rs, easytier/src/easytier-core.rs, easytier/src/instance/virtual_nic.rs
The "tun0" interface is too common, leading to potential conflicts.
=> support change tun interface name

easytier/locales/app.yml, easytier/src/common/config.rs, easytier/src/connector/direct.rs, easytier/src/connector/udp_hole_punch.rs, easytier/src/easytier-core.rs, easytier/src/peers/foreign_network_manager.rs, easytier/src/peers/peer_manager.rs
1. disable_p2p: only using specified peers to relay packets.
2. relay_all_peer_rpc: allow relay route info for networks not in whitelist
=> add two cmd line option

Cargo.lock, easytier-gui/src-tauri/src/lib.rs, easytier/Cargo.toml, easytier/src/common/mod.rs, easytier/src/common/scoped_task.rs, easytier/src/connector/udp_hole_punch.rs, easytier/src/easytier-core.rs, easytier/src/vpn_portal/wireguard.rs, script/install.sh
the punching task creator doesn't check if the task is already
running, and may create many punching task to same peer node.
this patch also improve hole punching by checking hole punch packet
even if punch rpc is failed.
=> fix punching task leak

easytier/Cargo.toml
command: 
```
cargo install --git https://github.com/EasyTier/EasyTier.git easytier
```
error: 
```
error: the `cargo::` syntax for build script output instructions was added in Rust 1.77.0, but the minimum supported Rust version of `easytier v1.2.3 (/Users/rui/.cargo/git/checkouts/easytier-54d55767af537c07/096ed39/easytier)` is 1.77.
```
change `1.77` to `1.77.0` in `easytier/Cargo.toml`
=> fix compile error due to rust version format

easytier-gui/src/components/Status.vue
https://github.com/EasyTier/EasyTier/issues/293 修复设备中转时判断条件不足导致显示为本机
=> 🐞 fix: GUI relay display error

easytier/src/easytier-core.rs
1. remove some unessesary copy in cli parse code of string
2. make some member function into non-member function to avoid taking the self reference.
3. use if let Some(..) instead of if xxx.is_some() to avoid copy and unwrap
=> making cli parse code more ergonomic by remove some copy and unwrap

easytier-gui/locales/cn.yml, easytier-gui/locales/en.yml, easytier-gui/src-tauri/src/lib.rs, easytier-gui/src/components/Config.vue, easytier-gui/src/types/network.ts
handle #285 
in the old behavior, the flags is not set, and it will be generated as default value in the first read. so the default value for the latency_first will be set to true according to the Default settings to Flag.
so the Vue code init the latency first to true.
=> add the options to enable latency first or not

script/install.sh
I noticed that there is an additional n here
=> Fix spelling errors

easytier/src/common/global_ctx.rs, easytier/src/instance/virtual_nic.rs
On Windows, newly added virtual network cards are set to "Public network" by default, causing the Windows built-in firewall to reject all inbound traffic from the virtual network card. Many services, such as Samba, Remote Desktop, Jellyfin are affected by this.
Changing the Category of the TUN device's network profile to 1 in Windows Registry makes it to be "Private network".
=> Set Category of the TUN device's network profile to 1 in Windows Registry

easytier-gui/package.json, easytier-gui/pnpm-lock.yaml, easytier-gui/src/components/Status.vue, easytier-gui/src/types/network.ts, easytier/src/proto/common.proto, easytier/src/proto/common.rs
To parse IP addresses from integers, `ip-num` was introduced as a dependency.
And because Tauri cannot handle the conversion from Rust's `uint64` to TypeScript's `bigint` properly, I have to break the `Ipv6Addr` protobuf message down to 4 parts so that every part will not overflow the `MAX_SAFE_INTEGER` of TypeScript's `number`.
=> Fix IP address display in the Status page of GUI

easytier/src/peers/peer_ospf_route.rs, easytier/src/proto/peer_rpc.proto
introduce my peer route id and peer id is duplicated only when peer
route id is not same.
this problem occurs because update_self may increase my peer info
version and propagate to other nodes.
=> fix #367, panic because of duplicated peer id

script/install.sh
In many Linux containers, curl is not installed by default, just like unzip.
look like it:
=> add curl dependency check in the installation script

easytier/src/common/stun.rs
In my network environment, `stunserver.stunprotocol.org` somehow resolved to `[::1]` and caused panic in [`stun.rs:L67`](https://github.com/EasyTier/EasyTier/blob/63821e56bccf12b59e0ddd3173629835e51a0406/easytier/src/common/stun.rs#L67).
This PR fix the panic issue.
=> Fix panic when DNS resolution for STUN server returns only IPv6 addrs.

script/install.sh
`ghproxy.com` 已被 gfw，替用 [ghp.ci](https://ghp.ci/)
=> 🐳 chore: proxy

easytier/locales/app.yml, easytier/src/easytier-cli.rs, easytier/src/lib.rs, easytier/src/utils.rs
when panic happend, previouse panic info:
panic occurred: PanicHookInfo { payload: **Any { .. },** location: Location { file: "easytier/src/easytier-core.rs", line: 680, col: 9 }, can_unwind: true, force_no_backtrace: false }
the new panic info:
panic occurred: payload:launcher error: "anyhow error: failed to add listener tcp://0.0.0.0:11010", location: Some(Location { file: "easytier/src/easytier-core.rs", line: 680, col: 9 })
backtrace saved to easytier-panic.log
=> make the panic message more useful

easytier/src/peers/peer_conn.rs, easytier/src/tunnel/common.rs
before this patch, invalid packat received by tunnel reader may cause a dead loop in handshake.
=> fix high cpu usage when client proto mismatch

easytier/src/proto/rpc_impl/packet.rs
every rpc packet should contains descriptor if sent to old version et.
=> fix peer rpc compatibility issue

Cargo.lock, easytier/Cargo.toml, easytier/build.rs, easytier/src/connector/udp_hole_punch/sym_to_cone.rs, easytier/src/peers/peer_conn_ping.rs, easytier/src/peers/peer_ospf_route.rs, easytier/src/proto/mod.rs, easytier/src/proto/rpc_impl/client.rs, easytier/src/proto/rpc_impl/server.rs, easytier/src/proto/rpc_types/controller.rs
prost doesn't support unknown field, and these info may be lost when
they go through a old version node.
=> forward original peer info in ospf route

easytier/locales/app.yml, easytier/src/common/config.rs, easytier/src/common/global_ctx.rs, easytier/src/easytier-core.rs, easytier/src/instance/instance.rs, easytier/src/proto/common.proto
In the current implementation of the proxy network feature, an internal NAT is used to enable non-gateway devices to participate in point-to-network networking, which is a fantastic functionality. However, for gateway devices, NAT is unnecessary, and its use can prevent accurate tracing of packets back to their source.
Therefore, in this PR, the `--proxy-forward-by-system` option has been added to directly deliver proxy network packets to the NIC device, allowing the system kernel to handle the packets forwarding. Additionally, delegating NAT to the system kernel instead of performing it in user space may offer some performance improvements (unverified).
=> allow proxy packets to be forwarded by system kernel

.github/workflows/test.yml, Cargo.lock, easytier/src/connector/dns_connector.rs, easytier/src/connector/http_connector.rs, easytier/src/connector/manual.rs
1. use ipv4 first when connect to http server.
2. allow redirect to url like: http://tcp://p.com:11010
3. dns should also use long timeout
=> improve http connector

easytier/src/web_client/session.rs
- .to_string(): `2025-03-19 18:41:15.291050 +08:00`
- .to_rfc3339(): `2025-03-19T18:41:14.776855+08:00`
=> fix(web_client): 将报告时间格式从字符串更改为RFC 3339格式

easytier-web/frontend/src/components/DeviceManagement.vue, easytier-web/src/client_manager/mod.rs, easytier/src/easytier-core.rs, easytier/src/web_client/controller.rs, easytier/src/web_client/mod.rs, easytier/src/web_client/session.rs
Use `--hostname xxx` to set the device name when connecting to config-server, so that you can easily identify the device on the DeviceList web page when it‘s inconvenient to modify the device hostname in the os。If not set, use the device hostname as the default value。
For example:
```shell
easytier-core -w udp://127.0.0.1:22020/user --hostname MyDevice
```
Fill the `hostname` field with the value of `--hostname` when creating new network in web
=> set hostname when connecting to config-server

easytier/Cargo.toml, easytier/src/easytier-core.rs
close #345 
supercedes #709 
Allow configure easytier from os environment variables `ET_*` (with same names as CLI args). e.g.
```bash
export ET_NETWORK_NAME="test"
export ET_NETWORK_SECRET="secret"
export ET_PEERS="tcp://public.easytier.cn:11010,tcp://example.com:11010"
easytier-core
```
A more common usage is in systemd services or Docker env files. e.g. 
```yaml
services:
easytier:
image: easytier/easytier:latest
network_mode: host
devices:
- /dev/net/tun
cap_add:
- NET_ADMIN
volumes:
- /share/Container/easytier:/root
environment:
ET_CONFIG_SERVER: example
restart: unless-stopped
```
Furthermore, this pr implement the feature that allows CLI args to override configurations from the config file, as described in #345
=> config from environment variables; CLI args override config file

easytier/locales/app.yml, easytier/src/common/config.rs, easytier/src/easytier-core.rs
在 #755 合并前，使用不含listeners字段的配置文件运行时默认行为为listeners置空
在 #755 合并后，存在由默认cli args带来的bug，配置文件的listeners无效
本pr产生的行为如下：
- CLI args中设置listeners时，以CLI args为准
- 否则，若配置文件中设置了listeners，以配置文件为准
- 若CLI args与配置文件均未设置listeners，设置默认listeners（11010/11011/11012）
*: 顺便更新了一下--help信息
=> fix default listeners for config file

easytier/src/common/stun.rs, easytier/src/utils.rs
1. backtrace may fail on some platform such as armv7, should do it last in panic hook.
2. stun should not panic when bind v6 failed.
=> fix panic cause segment fault

easytier/src/common/dns.rs, easytier/src/common/mod.rs, easytier/src/common/stun.rs, easytier/src/connector/dns_connector.rs, easytier/src/connector/mod.rs, easytier/src/instance/dns_server/server.rs, easytier/src/tunnel/common.rs, easytier/src/tunnel/mod.rs, easytier/src/tunnel/quic.rs, easytier/src/tunnel/ring.rs, easytier/src/tunnel/tcp.rs, easytier/src/tunnel/udp.rs, easytier/src/tunnel/websocket.rs, easytier/src/tunnel/wireguard.rs
1. dns resolver should be global unique so dns cache can work. avoid dns query influence hole punching.
2. when system dns failed, fallback to hickory dns.
=> fix dns query

easytier/src/easytier-cli.rs
在 cli 根命令添加了一个-o/--output选项，对于已支持表格数据的子命令添加了json输出的支持，如
- easytier-cli -o json peer list
- easytier-cli -o json route list
- easytier-cli -o json peer-center
- easytier-cli -o json proxy
close #497 
close #809
=> easytier-cli部分命令支持json输出

easytier-web/frontend/index.html, easytier-web/frontend/src/modules/api-host.ts, easytier-web/frontend/vite.config.ts, easytier-web/locales/app.yml, easytier-web/src/main.rs, easytier-web/src/restful/mod.rs, easytier-web/src/web/mod.rs
本 PR 主要通过以下几个改动实现了自定义 API 服务器地址的功能：
1. **命令行参数扩展**: 在 `easytier-web` 中新增 `--api-host` 参数，允许用户指定 Web 前端连接的 API 服务器地址
2. **动态 API 元数据注入**: 
- 新增 `/api_meta.js` 端点，动态生成包含 API 服务器地址的 JavaScript 配置
- 在 HTML 中引入该脚本，向前端注入 `window.apiMeta` 全局变量
3. **前端 API Host 自适应**:
- 重构 `easytier-web/frontend/src/modules/api-host.ts` 模块，实现智能地址选择策略
- 提供降级机制：本地存储历史地址 → 服务器注入地址（--api-host参数） → 当前访问地址
- **未使用 --api-host 参数时**：服务器不会注入 `window.apiMeta`，前端会优先使用历史地址，没有历史记录时使用当前访问地址
* 启用embed，web-server-port与api-server-port相同（或为空）：无需配置`api-host`参数，`/api_meta.js`返回`404`，当前访问地址作为API地址，能够正常使用。
* 启用embed，web-server-port与api-server-port不同：需要配置`api-host`参数，否则无法正常连接到API服务器。此时`/api_meta.js`会注入指定的API地址，前端将使用该地址进行API请求。
* 禁用embed：仅提供API服务，无Web界面。针对类似官方服务器这种web服务器与API服务器分离，但又没启用embed的场景，可以选择在web服务器中手动创建一个 `/api_meta.js` 文件，内容为 …
=> 支持通过 --api-host 参数自定义 Web 前端的 API 服务器地址

easytier-web/frontend-lib/src/components/Status.vue, easytier-web/frontend-lib/src/locales/cn.yaml, easytier-web/frontend-lib/src/locales/en.yaml
理论上web和gui都会加上，但我本地启不起来gui，因此只测了web。
另外是否考虑允许表格横向滚动？不然的话有些字换行了挤在一起不大好看。如果需要我一起加一下。
close #922
=> 节点信息组件添加隧道协议字段

easytier-web/frontend-lib/src/components/Config.vue, easytier-web/frontend-lib/src/locales/cn.yaml, easytier-web/frontend-lib/src/locales/en.yaml, easytier-web/frontend-lib/src/types/network.ts, easytier/locales/app.yml, easytier/src/common/config.rs, easytier/src/easytier-core.rs, easytier/src/instance/dns_server/server_instance.rs, easytier/src/instance/instance.rs, easytier/src/launcher.rs, easytier/src/proto/rpc_impl/standalone.rs, easytier/src/proto/web.proto
当前RPC门户默认绑定在 0.0.0.0 上，存在安全风险：
- 局域网设备 - 家庭网络相对安全，但公共WiFi等不可信网络存在风险
- EasyTier网络内其他节点 - 可能包含不可信设备
- 互联网用户 - 若设备具有公网IP，全球可访问
RPC接口暴露敏感信息（如 vpn-portal 等）
未授权用户可能获取网络配置信息
潜在的远程控制风险
将RPC门户默认绑定改为 127.0.0.1，遵循最小权限原则：
- 默认安全：仅本机可访问
- 符合常见用法：大多数用户仅需本地访问
- 灵活配置：有需要时可手动指定其他地址
- 命令行参数
默认绑定：127.0.0.1:15888
自定义绑定：支持 ip:port 格式（如 0.0.0.0:15888、192.168.1.10:15888）
- Web配置
配置下发时默认生成 127.0.0.1 绑定
配置生成器同步更新默认值
是否需要同步修改WebUI，将端口输入框改为 ip:port，以允许用户通过web配置时也能指定到其他地址？
close #925
=> 添加RPC门户白名单功能，默认仅允许本地访问，以增强安全性

easytier/src/instance/instance.rs
The current implementation continues to use TCP/UDP/ICMP proxies even when --proxy-forward-by-system is specified, due to the peer also being configured as an exit node.
However, with proper iptables and iproute2 configuration, traffic routed through an exit node can still be handled by the system's network stack without relying on userspace proxies.
This patch relaxes the condition and allows forwarding as long as a TUN device is present.
=> Allow using `--proxy-forward-by-system` together with `--enable-exit-node`

.github/workflows/core.yml, .github/workflows/test.yml, Cargo.lock, easytier-web/frontend-lib/src/components/Config.vue, easytier-web/frontend-lib/src/locales/cn.yaml, easytier-web/frontend-lib/src/locales/en.yaml, easytier-web/frontend-lib/src/types/network.ts, easytier/Cargo.toml, easytier/locales/app.yml, easytier/src/common/config.rs, easytier/src/common/global_ctx.rs, easytier/src/easytier-cli.rs, easytier/src/easytier-core.rs, easytier/src/gateway/kcp_proxy.rs, easytier/src/gateway/mod.rs, easytier/src/gateway/quic_proxy.rs, easytier/src/gateway/tcp_proxy.rs, easytier/src/instance/instance.rs, easytier/src/instance/listeners.rs, easytier/src/launcher.rs, easytier/src/peers/peer_map.rs, easytier/src/peers/peer_ospf_route.rs, easytier/src/peers/route_trait.rs, easytier/src/proto/cli.proto, easytier/src/proto/common.proto, easytier/src/proto/peer_rpc.proto, easytier/src/proto/web.proto, easytier/src/tests/three_node.rs, easytier/src/tunnel/packet_def.rs, easytier/src/tunnel/quic.rs
QUIC proxy works like kcp proxy, it can proxy TCP streams and transfer data with QUIC.
QUIC has better congestion algorithm (BBR) for network with both high loss rate and high bandwidth. 
QUIC proxy can be enabled by passing `--enable-quic-proxy` to easytier in the client side. The proxy status can be viewed by `easytier-cli proxy`.
=> support quic proxy

easytier/build.rs, easytier/src/proto/common.rs
修改了下面几个
1. common.Ipv4Addr
2. common.Ipv6Addr
3. common.UUID
日志中出现一堆u32实在太鬼畜了。
=> 为部分prost_build生成的结构体实现自定义fmt::Debug

easytier-web/frontend/src/components/ConfigGenerator.vue
移除了`bg-gray-100`并将样式调整为与web中的配置编辑弹窗基本保持一致
=> 修复配置生成器右侧输入框在夜间模式下背景是白色的问题

Cargo.lock, easytier-gui/src-tauri/Cargo.toml, easytier-gui/src-tauri/src/lib.rs
use elevated-command = "1.1.2" instead of privilege = "0.3" to fix gui elevation not popup issue
手头只有linux开发环境，所以windows/macos/安卓没有测试，理论上两个crate的平台支持能力完全相同
另外linux上开机自动启动似乎也有问题，还有通过终端启动程序后，退出的清理似乎并不顺利，还需要一些测试和优化
=> fix: cannot start gui on linux

.cargo/config.toml, .github/workflows/core.yml, .github/workflows/install_rust.sh
我们需要在 Linux RISC-V 64 平台上部署 EasyTier，所以希望 EasyTier 能够提供 `riscv64gc-unknown-linux-musl` 目标的分发。
本 PR 我已经测试过，能够正常构建 ([GitHub Action 日志](https://github.com/Glavo/EasyTier/actions/runs/16543671076/job/46788382385))，并且在 Milk-V Megrez (CPU 是 EIC7700X) 上能够正常工作。
=> Add support for Linux RISC-V 64

easytier/src/common/acl_processor.rs, easytier/src/common/config.rs, easytier/src/easytier-cli.rs, easytier/src/easytier-core.rs, easytier/src/gateway/socks5.rs, easytier/src/instance/instance.rs, easytier/src/peers/rpc_service.rs, easytier/src/proto/cli.proto
1. manage port forward:
```
./easytier-cli port-forward add tcp 0.0.0.0:54321 123.123.123.21:22
./easytier-cli port-forward remove tcp 0.0.0.0:54321 123.123.123.21:22
```
2. manage port whitelist:
```
./easytier-cli port-whitelist set-tcp 111-113
./easytier-cli port-whitelist clear-tcp
```
=> cli for port forward and tcp whitelist

easytier-gui/src-tauri/gen/android/app/src/main/AndroidManifest.xml, easytier-gui/src-tauri/gen/android/app/src/main/java/com/kkrainbow/easytier/MainActivity.kt, easytier-gui/src-tauri/gen/android/app/src/main/java/com/kkrainbow/easytier/MainForegroundService.kt, easytier-gui/src/composables/mobile_vpn.ts, easytier-gui/src/pages/index.vue
1. add FOREGROUND_SERVICE related code, connection not to be **blocked by android system** when apps running in background
2. no_tun mode not enabling vpnservice, makeing other app to use vpnservice
issue releated: 
https://github.com/EasyTier/EasyTier/issues/1021 
https://github.com/EasyTier/EasyTier/issues/689
1. 增加前台FOREGROUND_SERVICE的相关代码，避免应用进入后台后网络断开等问题
2. no_tun 模式(勾选socks5做代理)，只是一个普通的后台服务，不启动vpnservice，这样就能允许其他app使用vpnservice服务 
实测2台安卓环境勾选了 enable-kcp-proxy 和use_smoltcp 能够p2p直连
=> add FOREGROUND_SERVICE for no_tun mode, not using vpn service

easytier/src/arch/windows.rs, easytier/src/common/config.rs, easytier/src/common/global_ctx.rs, easytier/src/common/ifcfg/win/types.rs, easytier/src/common/ifcfg/windows.rs, easytier/src/common/stun.rs, easytier/src/easytier-cli.rs, easytier/src/easytier-core.rs, easytier/src/instance/dns_server/system_config/windows.rs, easytier/src/instance/virtual_nic.rs, easytier/src/utils.rs
This patch adds the functionality to support a custom STUN server list configuration, allowing users to have full control over outgoing traffic.
=> Support custom STUN servers configuration

easytier/src/common/config.rs, easytier/src/easytier-core.rs
- Hide default STUN Server configuration from cli logs.
- Hack the clap output for empty Vec<>
=> core: hide default STUN servers from cli

easytier/src/easytier-cli.rs
- Add short column names for latency, loss rate, rx/tx bytes, tunnel protocol and NAT type
- Format loss rate as percentage with one decimal place
- Change table style from modern to markdown for better readability
=> cli: improve peer table display with shorter columns for small display

easytier/src/instance/dns_server/server_instance.rs
为解决 resolve #1419 ，在内部直接读取 DNS 请求包并发回响应，而不是转发给监听端口。
- fake_ip (100.100.100.101) 上的 DNS 服务不再支持 DNS-over-TCP
- ~~现在可以向 fake_ip 的任意 UDP 端口请求 DNS~~
- ~~暂时保留 hickory-dns 对 tun_ip 动态端口的监听，未来可以作为可选功能，让 DNS 服务器监听指定 IP/端口~~
=> refactor: change magicdns to internal redirect

easytier/src/peers/peer_ospf_route.rs, easytier/src/tests/three_node.rs
问题: 当 ACL 入站规则的目标组或出站规则的来源组被设置时，该规则无法被正确匹配，导致ACL策略失效。
原因: ACL 组的缓存信息中，未包含该组自身的数据，使得在规则匹配时无法识别自己。
修复: 已修复此问题，但节点信息更新时，同时将自身组信息更新进缓存中，确保 ACL 组的缓存信息总是包含其自身，保障规则匹配的准确性。
close #1443
=> fix(acl): acl group cache add self group info
