EasyTier/EasyTier

.github/workflows/rust.yml, easytier-core/src/common/stun.rs, easytier-core/src/connector/udp_hole_punch.rs, easytier-core/src/instance/virtual_nic.rs
support CI with github actions.
=> GitHub actions

easytier-core/Cargo.toml, easytier-core/src/main.rs, easytier-core/src/peers/peer.rs, easytier-core/src/peers/peer_conn.rs
- elastic ping pong to adapt env with packet loss
- remove enable log
- fix not exit bug
- fix
- fix
=> fix elastic pingpong

easytier-cli/Cargo.toml, easytier-cli/src/main.rs, easytier-core/src/peers/peer_conn.rs
=> optimize cli output

easytier-core/src/tunnels/common.rs, easytier-core/src/tunnels/tcp_tunnel.rs, easytier-core/src/tunnels/udp_tunnel.rs
- mac bind device
- bind socket to device on macos
=> bind socket to device on macos

easytier-core/src/tunnels/stats.rs
- mac bind device
- bind socket to device on macos
- optimize latency window stats
=> optimize latency window stats

.cargo/config
=> Update cargo config

easytier-core/src/instance/instance.rs, easytier-core/src/peers/mod.rs, easytier-core/src/peers/peer_manager.rs, easytier-core/src/peers/peer_map.rs, easytier-core/src/peers/peer_rip_route.rs, easytier-core/src/peers/route_trait.rs, easytier-core/src/peers/tests.rs
- introduce peer center
- refactor route so we can add other router
=> peer center

easytier-core/src/connector/udp_hole_punch.rs, easytier-core/src/peers/peer_manager.rs, easytier-core/src/peers/peer_rip_route.rs, easytier-core/src/tunnels/udp_tunnel.rs
reduce bandwidth usage on route propagation
=> add version to rip route

easytier-core/src/common/stun.rs, easytier-core/src/peer_center/instance.rs, easytier-core/src/peer_center/server.rs, easytier-core/src/peers/peer_rip_route.rs
1. stable stun test result
2. stable report peers result
=> optimize bandwidth usage

easytier-cli/src/main.rs, easytier-core/proto/cli.proto, easytier-core/src/common/error.rs, easytier-core/src/common/global_ctx.rs, easytier-core/src/common/mod.rs, easytier-core/src/connector/direct.rs, easytier-core/src/connector/manual.rs, easytier-core/src/connector/udp_hole_punch.rs, easytier-core/src/gateway/icmp_proxy.rs, easytier-core/src/gateway/udp_proxy.rs, easytier-core/src/instance/instance.rs, easytier-core/src/instance/virtual_nic.rs, easytier-core/src/peer_center/instance.rs, easytier-core/src/peer_center/server.rs, easytier-core/src/peer_center/service.rs, easytier-core/src/peers/foreign_network_client.rs, easytier-core/src/peers/foreign_network_manager.rs, easytier-core/src/peers/mod.rs, easytier-core/src/peers/packet.rs, easytier-core/src/peers/peer.rs, easytier-core/src/peers/peer_conn.rs, easytier-core/src/peers/peer_manager.rs, easytier-core/src/peers/peer_map.rs, easytier-core/src/peers/peer_rip_route.rs, easytier-core/src/peers/peer_rpc.rs, easytier-core/src/peers/route_trait.rs, easytier-core/src/peers/rpc_service.rs, easytier-core/src/peers/tests.rs, easytier-core/src/tests/mod.rs, easytier-core/src/tests/three_node.rs
prepare to optimize route propogation algo.
=> use uint32 as peer id

easytier-core/Cargo.toml, easytier-core/proto/cli.proto, easytier-core/src/connector/direct.rs, easytier-core/src/connector/udp_hole_punch.rs, easytier-core/src/gateway/icmp_proxy.rs, easytier-core/src/gateway/tcp_proxy.rs, easytier-core/src/gateway/udp_proxy.rs, easytier-core/src/instance/instance.rs, easytier-core/src/main.rs, easytier-core/src/peer_center/instance.rs, easytier-core/src/peers/foreign_network_client.rs, easytier-core/src/peers/foreign_network_manager.rs, easytier-core/src/peers/mod.rs, easytier-core/src/peers/peer_manager.rs, easytier-core/src/peers/peer_map.rs, easytier-core/src/peers/peer_ospf_route.rs, easytier-core/src/peers/peer_rip_route.rs, easytier-core/src/peers/peer_rpc.rs, easytier-core/src/peers/rpc_service.rs, easytier-core/src/peers/tests.rs, easytier-core/src/tests/mod.rs
distance vector routing algo has bad perf in some scenorios:
1. peer disconnect.
2. peers are connected full mesh.
3. large amount peer in one network
this patch introduce a link state route algo to resolve these problem.
=> introduce a link-state route algo

easytier-core/src/connector/direct.rs, easytier-core/src/peers/peer_ospf_route.rs
fix direct connector use ring,
=> fix ipv4 map use old peer_id

Cargo.toml, README.md, README_CN.md, src/connector/direct.rs, src/connector/manual.rs, src/connector/mod.rs, src/easytier-core.rs, src/instance/listeners.rs, src/tests/three_node.rs, src/tunnels/common.rs, src/tunnels/mod.rs, src/tunnels/udp_tunnel.rs, src/tunnels/wireguard.rs
peers can connect with each other using wireguard protocol.
=> add wireguard tunnel

Cargo.toml, proto/cli.proto, src/common/config.rs, src/common/global_ctx.rs, src/common/mod.rs, src/common/stun.rs, src/easytier-cli.rs, src/easytier-core.rs, src/instance/instance.rs, src/peer_center/instance.rs, src/peers/foreign_network_manager.rs, src/peers/peer_ospf_route.rs, src/peers/peer_rip_route.rs, src/tunnels/udp_tunnel.rs, src/tunnels/wireguard.rs, src/vpn_portal/mod.rs, src/vpn_portal/wireguard.rs
allow wireguard client connecting to the easytier network
=> Support wireguard vpn portal

Cargo.toml, src/arch/windows.rs, src/common/constants.rs, src/common/network.rs, src/connector/direct.rs, src/easytier-core.rs, src/peers/peer_conn.rs, src/tunnels/common.rs, src/tunnels/mod.rs, src/tunnels/udp_tunnel.rs, src/tunnels/wireguard.rs
- **improve udp tunnel listener**
- **use custom panic handler**
=> fix udp listen

easytier/src/common/global_ctx.rs, easytier/src/connector/manual.rs, easytier/src/easytier-core.rs, easytier/src/instance/instance.rs
1. fix manual connector do not retry if dns resolve failed.
2. allow not creating tun device if no virtual ipv4 is assigned.
=> bug fix and improve

easytier/src/common/config.rs, easytier/src/easytier-core.rs, easytier/src/instance/virtual_nic.rs, easytier/src/peers/encrypt/aes_gcm.rs, easytier/src/peers/encrypt/mod.rs, easytier/src/peers/encrypt/ring_aes_gcm.rs, easytier/src/peers/peer_manager.rs, easytier/src/utils.rs
- **correctly set mtu, and allow set mtu manually**
- **communicate between enc and non-enc should not panic**
- **allow loading cfg from file**
- **allow change file log level dynamically**
=> fix bugs and improve user experiance

easytier/src/connector/manual.rs
if join_next stuck, may miss global event and cause panic
=> remove reconn task set

easytier/src/instance/instance.rs
on win 10, tcp proxy listener created before tun device may not accept
conn from tun dev.
=> start tcp proxy after tun device created

easytier/src/instance/virtual_nic.rs
fix https://github.com/EasyTier/EasyTier/issues/110#issue-2291968878
=> 🐞 fix: same tun name

Cargo.lock, easytier/Cargo.toml, easytier/src/common/ifcfg.rs, easytier/src/utils.rs
修复中文环境下命令行输出为 gbk 导致 utf8 解析出现口字乱码
=> 🐞 fix: cmd error with gbk

easytier/src/common/config.rs, easytier/src/common/ifcfg.rs, easytier/src/instance/virtual_nic.rs, easytier/src/tunnel/wireguard.rs
1. fix mtu, always set by ourselves and use smaller value
2. wireguard connector should return tunnel after receive packet
=> fix mtu and wireguard connector

easytier/src/common/config.rs, easytier/src/easytier-core.rs, easytier/src/gateway/icmp_proxy.rs, easytier/src/gateway/tcp_proxy.rs, easytier/src/gateway/udp_proxy.rs, easytier/src/instance/instance.rs, easytier/src/peers/peer_manager.rs, easytier/src/tunnel/packet_def.rs
support exit node, proxy all traffic via one of node
NOTE: this patch has not implemented automatically route management.
=> support exit node

easytier/proto/cli.proto, easytier/src/common/defer.rs, easytier/src/common/mod.rs, easytier/src/common/netns.rs, easytier/src/common/stun.rs, easytier/src/common/stun_codec_ext.rs, easytier/src/connector/udp_hole_punch.rs, easytier/src/easytier-cli.rs, easytier/src/peers/peer_conn_ping.rs, easytier/src/tunnel/udp.rs
1. implement new stun test algorithm do test faster and provide more info
2. improve hole punching, support nat4 -> nat3 punch
=> improve hole punching and stun test

.github/workflows/core.yml, .github/workflows/test.yml, Cargo.lock, Cargo.toml, easytier/Cargo.toml, easytier/src/common/global_ctx.rs, easytier/src/common/network.rs
- **make release bin smaller**
=> optimize binary size

Cargo.lock, easytier/Cargo.toml, easytier/src/instance/virtual_nic.rs
win7 must have following updates installed:
1. Service Pack 1 (SP1)
2. KB4474419: https://www.youwindowsworld.com/en/downloads/operating-systems/windows-7/update-windows-7-kb4474419/
=> support win7 and reduce win mem usage

easytier/src/connector/mod.rs, easytier/src/tunnel/websocket.rs
- **websocket support bind addr**
=> websocket bind

.cargo/config.toml, .github/workflows/core.yml, .github/workflows/install_rust.sh, Cargo.lock, README.md, README_CN.md, easytier-gui/src/components/Config.vue, easytier-gui/src/components/Status.vue, easytier-gui/src/pages/index.vue, easytier/Cargo.toml, easytier/src/instance/instance.rs, easytier/src/instance/virtual_nic.rs, easytier/src/peers/peer_rpc.rs
1. GUI: use correct i18n hook
2. fix peer rpc panic
3. fix dhcp: recreate tun device after ip changed
4. use upx correctly in worflow
=> bugfix before release 11x

.github/workflows/core.yml, easytier/src/connector/udp_hole_punch.rs, easytier/src/peer_center/instance.rs, easytier/src/peers/peer_manager.rs, easytier/src/peers/peer_ospf_route.rs, easytier/src/peers/peer_rpc.rs, easytier/src/peers/tests.rs, easytier/src/tests/three_node.rs, easytier/src/tunnel/common.rs, easytier/src/tunnel/udp.rs
- **fix upx in workflow**
- **fix udp conn counter, should decrease after conn close**
=> fix upx and udp conn counter

Cargo.lock, easytier-gui/locales/cn.yml, easytier-gui/locales/en.yml, easytier-gui/src-tauri/Cargo.toml, easytier-gui/src-tauri/src/main.rs, easytier-gui/src/auto-imports.d.ts, easytier-gui/src/composables/network.ts, easytier-gui/src/main.ts, easytier-gui/src/modules/auto_launch.ts, easytier-gui/src/pages/index.vue, easytier-gui/src/stores/network.ts, easytier/Cargo.toml, easytier/src/common/ifcfg.rs, easytier/src/launcher.rs, easytier/src/lib.rs
- **move launcher to eastier lib**
- **gui support start on reboot**
=> support start on reboot

easytier/src/common/global_ctx.rs, easytier/src/gateway/icmp_proxy.rs, easytier/src/gateway/tcp_proxy.rs, easytier/src/gateway/udp_proxy.rs
- **fix udp proxy not work when being exit node**
=> fix udp proxy for exit node

easytier/src/instance/instance.rs
1. fix dhcp not retry if tun device init failed.
2. forbid dhcp use default ip when no peer.
=> fix bug in dhcp

easytier/src/easytier-core.rs, easytier/src/gateway/tcp_proxy.rs, easytier/src/instance/instance.rs
1. allow smoltcp proxy with dhcp ip
2. fix smoltcp not work without no tun.
=> fix smoltcp tcp proxy

easytier-gui/src/composables/mobile_vpn.ts, tauri-plugin-vpnservice/android/src/main/java/TauriVpnService.kt
- **fix vpn close when getting new subnet route**
=> fix android vpn close after getting new route

easytier/src/common/config.rs, easytier/src/common/global_ctx.rs, easytier/src/easytier-core.rs, easytier/src/instance/virtual_nic.rs
use `--manual-routes` to diabled automatical route. also support args like `--manual-routes 192.168.94.0/24 192.168.1.0/24'` to assin manual routes
=> support manual routes

easytier-gui/src-tauri/src/lib.rs, easytier-gui/src-tauri/tauri.conf.json
=> fix two trayicon

easytier-gui/src-tauri/Cargo.toml, easytier-gui/src-tauri/src/lib.rs, easytier/Cargo.toml, easytier/src/instance/virtual_nic.rs
delete bloated registry items.
check and delete the registry when launching easytier-gui.
just making modifications to easytier-gui instead of easytier-core
=> delete bloated registry items

.github/workflows/core.yml, .github/workflows/gui.yml, .github/workflows/mobile.yml, easytier/src/common/global_ctx.rs, easytier/src/connector/udp_hole_punch.rs, easytier/src/easytier-core.rs, easytier/src/instance/listeners.rs, easytier/src/peers/peer_ospf_route.rs
currently session & session task in route algo is maintained separatedly, which may mismatch and causing stop propogate routing info.
=> fix session_task and session mismatch

.github/workflows/Dockerfile, .github/workflows/docker.yml
- **introduce docker image updater**
=> docker uploader

easytier/src/instance/instance.rs, tauri-plugin-vpnservice/android/src/main/java/TauriVpnService.kt
1. android correctly add route
2. use mock nic ctx to consume packets
=> fix android route and peer conn disconn bug

Cargo.lock, easytier-gui/src/composables/mobile_vpn.ts, easytier/Cargo.toml, easytier/src/instance/instance.rs, easytier/src/instance/virtual_nic.rs, tauri-plugin-vpnservice/android/src/main/java/TauriVpnService.kt
- **fix android route**
- **fix peer conn disconn bug**. use a mock nic ctx to consume nic packet from peer
- **use tun2**
=> use tun2 to replace meh/rust-tun

easytier-gui/src-tauri/src/lib.rs, easytier/src/easytier-core.rs, easytier/src/utils.rs
this helps collect gui crash info.
=> also setup panic handler on gui

easytier/Cargo.toml, easytier/locales/app.yml, easytier/src/common/config.rs, easytier/src/easytier-core.rs, easytier/src/gateway/fast_socks5/LICENSE, easytier/src/gateway/fast_socks5/README.md, easytier/src/gateway/fast_socks5/mod.rs, easytier/src/gateway/fast_socks5/server.rs, easytier/src/gateway/fast_socks5/util/mod.rs, easytier/src/gateway/fast_socks5/util/stream.rs, easytier/src/gateway/fast_socks5/util/target_addr.rs, easytier/src/gateway/mod.rs, easytier/src/gateway/socks5.rs, easytier/src/gateway/tokio_smoltcp/mod.rs, easytier/src/instance/instance.rs
usage: --socks5 12345
create an socks5 server on port 12345, can be used by socks5 client to access
virtual network.
=> support socks5 proxy

Cargo.lock, easytier/Cargo.toml, easytier/src/easytier-core.rs
rust-i18n 3.1.1 has bug:
https://github.com/longbridgeapp/rust-i18n/issues/87
=> fix i18n, revert rust-i18n to v3.0.1

Cargo.lock, easytier/Cargo.toml
- **update rust-i18n to v3.1.2**
=> update rust-i18n to v3.1.2

.github/workflows/release.yml, README.md, README_CN.md
=> add MacOS Homebrew installation method (#185)

script/easytier.sh
1. Add config support. And must use config file now
2. Support mulit-service management. Now use "easytier@xxx" to manage more service
3. Delete the port check in  script
=> Add config and mulit-service support to script and delete port check

easytier-gui/src-tauri/src/lib.rs, easytier/proto/cli.proto, easytier/src/connector/manual.rs, easytier/src/easytier-cli.rs, easytier/src/peers/peer_conn.rs, easytier/src/tests/three_node.rs
too many alive conns may cause high cpu usage and lagged broadcast
recv.
=> only add necessary conn to alive urls

easytier-gui/src/pages/index.vue
不知道这样修改是否是正确的。
这个URL可以预览到效果。
http://easytier-pr-preview-283.surge.sh/
=> fix: Different network methods server URL display

easytier/locales/app.yml, easytier/src/common/config.rs, easytier/src/connector/udp_hole_punch.rs, easytier/src/easytier-core.rs
在UDP打洞问题彻底修复前，通过这个配置项来禁用UDP打洞以缓解问题。
https://github.com/EasyTier/EasyTier/issues/289
=> 添加了一个配置项 "disable_udp_hole_punch" 来禁用UDP打洞功能

easytier/src/gateway/fast_socks5/mod.rs, easytier/src/tunnel/mpsc.rs, easytier/src/vpn_portal/wireguard.rs
wg portal doesn't know client disconnect causing msg overstocked in queue, make
entire peer packet process pipeline hang.
=> fix wg client hang after some time

easytier-gui/locales/cn.yml, easytier-gui/locales/en.yml, easytier-gui/src/components/Status.vue, easytier-gui/src/types/network.ts, easytier/proto/cli.proto, easytier/src/easytier-cli.rs, easytier/src/launcher.rs, easytier/src/peers/peer_conn.rs, easytier/src/peers/peer_manager.rs, easytier/src/peers/peer_ospf_route.rs
Add display version information, incompatible with lower versions
=> ✨ feat: show version & local node

easytier/src/gateway/udp_proxy.rs
- **fix udp proxy disconn unexpectedly**
=> fix udp proxy

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
github issue template bug & feature
=> 🐎 ci: github issue template

.github/workflows/gui.yml
github action upgraded the ubuntu-latest to 24.04
https://github.com/actions/runner-images/pull/10687
=> use ubuntu 24.04 apt source

easytier-gui/src-tauri/src/lib.rs, easytier-gui/src/components/Config.vue, easytier-gui/src/components/Status.vue, easytier-gui/src/composables/mobile_vpn.ts, easytier-gui/src/types/network.ts, easytier/src/peers/peer_conn.rs, easytier/src/peers/peer_ospf_route.rs, easytier/src/proto/rpc_impl/client.rs, easytier/src/proto/rpc_impl/server.rs, easytier/src/proto/tests.rs, easytier/src/tunnel/mpsc.rs, easytier/src/tunnel/ring.rs, easytier/src/vpn_portal/wireguard.rs
- **fix peer rpc stop working because of mpsc tunnel close unexpectedly**
- **fix gui:**
1. allow set network prefix for virtual ipv4
2. fix android crash
3. fix subnet proxy cannot be set on android
=> fix 202 bugs

easytier-gui/src-tauri/src/lib.rs, easytier/src/common/stun.rs, easytier/src/gateway/tokio_smoltcp/device.rs, easytier/src/launcher.rs, tauri-plugin-vpnservice/src/error.rs
Reproduce steps:
1. Open the app
2. Close the window
3. Click on the dock icon, the app won't show again
This patch fix it.
=> Fix app not displayed when click on the dock icon under macOS

easytier/locales/app.yml
=> fix mtu parameter prompt

easytier-gui/package.json, easytier-gui/pnpm-lock.yaml
=> 🐳 chore: vue

.gitignore, easytier/Cargo.toml, easytier/build.rs, easytier/src/easytier-cli.rs, easytier/src/easytier-core.rs, easytier/src/lib.rs, easytier/src/proto/mod.rs, easytier/src/tests/mod.rs
Make easytier-cli and easytier-core link to the easytier library to avoid duplicate linking of mods.
=> Optimize building speed

easytier-web/frontend-lib/src/components/Config.vue, easytier-web/frontend-lib/src/locales/cn.yaml, easytier-web/frontend-lib/src/types/network.ts, easytier/src/common/config.rs, easytier/src/launcher.rs, easytier/src/proto/web.proto, easytier/src/tests/three_node.rs
- **add test to kcp**
- **add more options**
=> add options to gui to enable kcp

Cargo.lock, easytier/src/common/global_ctx.rs, easytier/src/gateway/kcp_proxy.rs, easytier/src/gateway/tcp_proxy.rs, easytier/src/peers/peer_map.rs, easytier/src/peers/peer_ospf_route.rs, easytier/src/peers/route_trait.rs, easytier/src/proto/common.proto, easytier/src/tests/three_node.rs
- **fix kcp not work with smoltcp**
- **check if dst kcp input is enabled**
=> make kcp proxy compitible with old version

easytier-web/frontend-lib/src/modules/api.ts, easytier-web/frontend/src/components/ConfigGenerator.vue, easytier-web/frontend/src/main.ts, easytier-web/src/restful/mod.rs, easytier/src/easytier-cli.rs, easytier/src/gateway/icmp_proxy.rs, easytier/src/gateway/kcp_proxy.rs, easytier/src/gateway/tcp_proxy.rs, easytier/src/instance/instance.rs, easytier/src/launcher.rs, easytier/src/proto/cli.proto, easytier/src/proto/common.rs, easytier/src/proto/peer_rpc.proto
1. add config generator to easytier-web
2. add command to show tcp/kcp proxy entries
=> improve user experience

Cargo.lock, easytier/Cargo.toml, easytier/src/connector/http_connector.rs, easytier/src/connector/mod.rs, easytier/src/gateway/kcp_proxy.rs, easytier/src/tunnel/mod.rs
- **remove some dep**
- **http redirector**
=> http redirect

easytier/build.rs, easytier/src/common/mod.rs, easytier/src/peers/foreign_network_manager.rs, easytier/src/peers/peer_conn_ping.rs, easytier/src/peers/peer_ospf_route.rs, easytier/src/peers/peer_task.rs
JoinSet::poll_join_next does not wake up ctx when dropping.
=> fix memory leak

easytier/src/connector/http_connector.rs, easytier/src/connector/manual.rs, easytier/src/easytier-core.rs, easytier/src/lib.rs
- **make http connector timeout longer**
- **allow using http connector for config server**
=> optimize http connector

Cargo.lock, easytier/Cargo.toml, easytier/src/connector/dns_connector.rs, easytier/src/connector/mod.rs, easytier/src/easytier-core.rs, easytier/src/tunnel/mod.rs
=> support txt/srv record

easytier-web/src/main.rs
=> easytier-web add tcp support

easytier-web/frontend-lib/src/components/Config.vue, easytier-web/frontend-lib/src/components/Status.vue, easytier-web/frontend-lib/src/locales/cn.yaml, easytier-web/frontend-lib/src/locales/en.yaml, easytier-web/frontend-lib/src/style.css, easytier-web/frontend-lib/src/types/network.ts, easytier-web/frontend/src/components/DeviceList.vue, easytier-web/frontend/src/components/DeviceManagement.vue, easytier/src/launcher.rs, easytier/src/proto/web.proto
add configurable items for web
*  enable_exit_node
*  relay_all_peer_rpc
*  multi_thread
*  proxy_forward_by_system
*  relay_network_whitelist
* manual_routes
* exit_nodes
=> add configurable items for web

.github/workflows/core.yml, .github/workflows/gui.yml, .github/workflows/mobile.yml, easytier/src/gateway/tcp_proxy.rs, easytier/src/gateway/tokio_smoltcp/reactor.rs, easytier/src/gateway/tokio_smoltcp/socket.rs, easytier/src/proto/cli.proto, easytier/src/tests/three_node.rs, easytier/src/vpn_portal/wireguard.rs
This may cause smoltcp stop accepting new subnet proxy connection after running some time.
=> fix smoltcp not wakeup closed socket

easytier-web/frontend/src/components/DeviceList.vue, easytier-web/frontend/src/components/DeviceManagement.vue
1. fix network config exprot bug
2. format `Report Time` on the DeviceList page
=> fix web bugs

Cargo.lock, easytier/Cargo.toml, easytier/src/common/config.rs, easytier/src/common/stun.rs, easytier/src/connector/direct.rs, easytier/src/connector/dns_connector.rs, easytier/src/connector/manual.rs, easytier/src/connector/udp_hole_punch/common.rs, easytier/src/easytier-cli.rs, easytier/src/easytier-core.rs, easytier/src/instance/listeners.rs, easytier/src/peers/foreign_network_manager.rs, easytier/src/peers/peer.rs, easytier/src/peers/peer_manager.rs, easytier/src/peers/peer_map.rs, easytier/src/peers/rpc_service.rs, easytier/src/peers/tests.rs, easytier/src/proto/cli.proto, easytier/src/proto/cli.rs, easytier/src/proto/common.proto, easytier/src/tunnel/common.rs, easytier/src/tunnel/mod.rs, easytier/src/tunnel/tcp.rs, easytier/src/tunnel/udp.rs
- **tmp**
- **support ipv6 stun**
- **show interface and public ip in cli node info**
- **ipv6 fetch interval**
- **direct conn should keep trying unless already direct connected**
- **peer should use conn with smallest latency**
- **deprecate ipv6_listener, use -l instead**
- **move direct conn map to peer_manager**
=> improve direct connector

easytier/src/connector/dns_connector.rs, easytier/src/connector/udp_hole_punch/sym_to_cone.rs, easytier/src/tunnel/insecure_tls.rs, easytier/src/tunnel/websocket.rs
=> enable sni for tls client

easytier-web/frontend-lib/src/components/Config.vue, easytier-web/frontend-lib/src/locales/cn.yaml, easytier-web/frontend-lib/src/locales/en.yaml, easytier-web/frontend-lib/src/types/network.ts, easytier/src/launcher.rs, easytier/src/proto/web.proto
1. add disable_udp_hole_punching for web
2. hide network_secret by default #699
=> add disable_udp_hole_punching and hide passwd for web

easytier-web/frontend-lib/src/components/Config.vue, easytier-web/frontend-lib/src/locales/cn.yaml, easytier-web/frontend-lib/src/locales/en.yaml, easytier-web/frontend-lib/src/types/network.ts, easytier/src/launcher.rs, easytier/src/proto/web.proto
add mtu and mapped_listeners for web
=> add mtu and mapped_listeners for web

easytier-web/frontend/src/components/ConfigGenerator.vue, easytier-web/frontend/src/components/Login.vue, easytier-web/frontend/src/modules/api-host.ts
add ApiHost option for ConfigGenerator
=> add ApiHost option for ConfigGenerator

easytier-gui/locales/cn.yml, easytier-gui/locales/en.yml, easytier-web/frontend-lib/src/locales/cn.yaml, easytier-web/frontend-lib/src/locales/en.yaml, easytier-web/frontend-lib/src/types/network.ts, easytier/Cargo.toml, easytier/locales/app.yml, easytier/src/common/config.rs, easytier/src/common/global_ctx.rs, easytier/src/easytier-core.rs, easytier/src/gateway/ip_reassembler.rs, easytier/src/gateway/socks5.rs, easytier/src/gateway/tokio_smoltcp/mod.rs, easytier/src/gateway/tokio_smoltcp/socket.rs, easytier/src/gateway/tokio_smoltcp/socket_allocator.rs, easytier/src/instance/instance.rs, easytier/src/proto/common.proto, easytier/src/proto/common.rs, easytier/src/tests/three_node.rs, easytier/src/tunnel/common.rs
- **support tcp port forward**
- **support udp port forward**
=> port forward

.github/workflows/core.yml, .github/workflows/test.yml, Cargo.lock, easytier-web/Cargo.toml, easytier-web/locales/app.yml, easytier-web/src/main.rs, easytier-web/src/web/mod.rs
easytier-web-embed has the same functionality as easytier-web except that easytier-web-embed embeds web-dashboard. the web-dashboard server will listen on port `11210` by default, or run with `-l port` to change port.
For example:
```
easytier-web-embed -l 8888
```
=> add binary file easytier-web-embed

easytier-web/frontend-lib/src/types/network.ts, easytier/src/easytier-core.rs
https://github.com/EasyTier/EasyTier/issues/713
https://github.com/EasyTier/EasyTier/issues/735
=> perf: update default rpc_port value to 15888 in network configuration

README.md, README_CN.md, script/install.sh
- Add help information display feature
- Support custom GitHub proxy URL
- Add --no-gh-proxy option to disable GitHub proxy
- Optimize error messages and command prompts
- Fix typo (Commend -> Command)
=> feat(install): enhance installation script functionality

easytier/src/instance/listeners.rs
unspecified ipv6 listeners should not be added automatically for specified ipv4 listener
对于指定了地址的IPv4监听器，不应自动添加[::] IPv6监听器
=> fix: avoid add ipv6 listener automatically for specified ipv4 listener

Cargo.lock, Cargo.toml, easytier/Cargo.toml, easytier/src/peers/graph_algo.rs, easytier/src/peers/mod.rs, easytier/src/peers/peer_manager.rs, easytier/src/peers/peer_ospf_route.rs
this may fix following problem:
1. cpu 100% when large number of nodes in network.
2. high cpu usage when large number of foreign networks.
3. packet loss when new node enters/exits.
4. old routes not cleand and show as an obloleted entry.
=> improve performance of route generation

.cargo/config.toml, .github/workflows/core.yml, Cargo.lock, easytier/Cargo.toml, easytier/src/easytier-core.rs, easytier/src/peers/peer.rs, easytier/src/peers/peer_manager.rs, easytier/src/peers/peer_ospf_route.rs
1. update upx to v5.0.1 to avoid mips bug.
2. use latest mimalloc.
3. fix panic in ospf route
=> fix minor bugs

easytier/src/common/dns.rs, easytier/src/tunnel/mod.rs, easytier/src/tunnel/websocket.rs
=> Update default_port and sni logic to improve reverse proxy reachability

easytier/src/vpn_portal/wireguard.rs
This pull request addresses an issue where the vpn-portal module inadvertently removes a WireGuard client's peer entry when the client roams to a new remote address. Such roaming typically occurs during network transitions or NAT remapping.
In the current implementation, when a WireGuard client reconnects using the same internal IP address, the system updates the `wg_peer_ip_table` entry with the new connection's information, effectively overwriting the previous record. However, the old connection is still tracked separately.
Once the system later determines that the old connection is inactive, it proceeds to remove the corresponding entry from `wg_peer_ip_table` based on the now-stale reference. Since the table has already been overwritten by the new connection using the same IP address, …
=> fix(vpn-portal): wireguard peer table should be kept if the client roamed to another endpoint address

easytier-web/src/client_manager/mod.rs, easytier-web/src/main.rs
Easytier-web support listen dual stack.
=> Web dual stack

easytier/src/instance/virtual_nic.rs, easytier/src/peers/peer_ospf_route.rs
sometimes route table may not be updated in time, so some dead nodes are still showing in the peer list.
when generating ipv4-peer table, we should avoid these dead devices overrides the entry of healthy nodes.
=> ipv4-peerid table should use peer with least hop

Cargo.lock, easytier/Cargo.toml, easytier/locales/app.yml, easytier/src/common/config.rs, easytier/src/common/global_ctx.rs, easytier/src/common/stun.rs, easytier/src/connector/manual.rs, easytier/src/easytier-core.rs, easytier/src/gateway/icmp_proxy.rs, easytier/src/gateway/kcp_proxy.rs, easytier/src/gateway/mod.rs, easytier/src/gateway/socks5.rs, easytier/src/gateway/tcp_proxy.rs, easytier/src/gateway/udp_proxy.rs, easytier/src/instance/instance.rs, easytier/src/instance/listeners.rs, easytier/src/launcher.rs, easytier/src/peer_center/instance.rs, easytier/src/peer_center/mod.rs, easytier/src/peers/peer_manager.rs, easytier/src/peers/peer_ospf_route.rs, easytier/src/proto/rpc_impl/service_registry.rs, easytier/src/tests/three_node.rs
- **support mapping subproxy network cidr**
- **add command line option for proxy network mapping**
- **fix Instance leak in tests.
=> mapping subnet proxy

easytier/src/instance_manager.rs
由于GUI调用run_network_instance时不在tokio环境中，因此启动协程时会报错。
鉴于GUI不需要处理事件回调和自动删除instance，因此和FFI一样处理直接不启动协程
=> Fix panic issue when using InstanceManager with GUI

README.md, README_CN.md
=> fix easytier-gui

Cargo.lock, easytier/Cargo.toml, easytier/src/common/config.rs, easytier/src/common/global_ctx.rs, easytier/src/common/mod.rs, easytier/src/common/token_bucket.rs, easytier/src/easytier-core.rs, easytier/src/peers/foreign_network_manager.rs, easytier/src/peers/peer_manager.rs, easytier/src/proto/common.proto, easytier/src/tests/three_node.rs, easytier/src/tunnel/common.rs, easytier/src/tunnel/quic.rs
allow limit relay bps of foreign network
=> add bps limiter

easytier-gui/src/styles.css, easytier-web/frontend-lib/src/components/Config.vue, easytier-web/frontend-lib/src/locales/cn.yaml, easytier-web/frontend-lib/src/locales/en.yaml, easytier-web/frontend-lib/src/modules/i18n.ts, easytier-web/frontend-lib/src/style.css, easytier-web/frontend/index.html, easytier-web/frontend/package.json, easytier-web/frontend/src/App.vue, easytier-web/frontend/src/components/DeviceDetails.vue, easytier-web/frontend/src/components/DeviceList.vue, easytier-web/frontend/src/components/DeviceManagement.vue, easytier-web/frontend/src/components/Login.vue, easytier-web/frontend/src/components/MainPage.vue, easytier-web/frontend/src/main.ts, easytier-web/frontend/src/style.css, easytier-web/frontend/vite.config.ts, pnpm-lock.yaml
- **collapse side bar**
- **tmp**
- **tmp**
- **tmp**
- **t**
- **tmp**
- **test**
- **i18n**
=> web improve

Cargo.lock, Cargo.toml, EasyTier.code-workspace, easytier/Cargo.toml, easytier/src/common/ifcfg/darwin.rs, easytier/src/common/ifcfg/mod.rs, easytier/src/common/ifcfg/netlink.rs, easytier/src/common/ifcfg/win/luid.rs, easytier/src/common/ifcfg/win/mod.rs, easytier/src/common/ifcfg/win/netsh.rs, easytier/src/common/ifcfg/win/types.rs, easytier/src/common/ifcfg/windows.rs, easytier/src/easytier-core.rs, easytier/src/instance/virtual_nic.rs
can not execut netsh on some windows machines. also this avoid black cmd window when using gui
=> use winapi to config ip and route (remove dep on netsh)

easytier/src/connector/direct.rs, easytier/src/peers/foreign_network_manager.rs, easytier/src/peers/peer_manager.rs
when closing conn, should check all places.
=> handle close peer conn correctly

Cargo.lock, README.md, README_CN.md, easytier/Cargo.toml, easytier/locales/app.yml, easytier/src/easytier-cli.rs, easytier/src/easytier-core.rs, easytier/src/lib.rs
use clap-complete crate to generate completions scripts: easytier-core --generate fish > ~/.config/fish/completions/easytier-core.fish
=> add options to generate completions

easytier/src/arch/windows.rs, easytier/src/instance/virtual_nic.rs
allow all icmp/tcp/udp on tun interface.
=> add windows firewall for tun interface

easytier/src/connector/manual.rs, easytier/src/peers/peer_conn.rs
1. do not exit when dns query failed on et startup.
2. do not send secret digest to client when secret mismatch.
=> some improvement

Cargo.lock, easytier/src/common/config.rs, easytier/src/easytier-core.rs, easytier/src/instance/virtual_nic.rs, easytier/src/launcher.rs, easytier/src/peers/peer_manager.rs
properly handle ipv6 link local address and exit node.
=> fix ipv6 packet routing and avoid route looping

easytier/src/common/global_ctx.rs, easytier/src/common/mod.rs, easytier/src/common/stats_manager.rs, easytier/src/easytier-cli.rs, easytier/src/instance/instance.rs, easytier/src/peers/foreign_network_manager.rs, easytier/src/peers/peer_conn.rs, easytier/src/peers/peer_manager.rs, easytier/src/peers/peer_rpc.rs, easytier/src/proto/cli.proto, easytier/src/proto/rpc_impl/bidirect.rs, easytier/src/proto/rpc_impl/client.rs, easytier/src/proto/rpc_impl/server.rs, easytier/src/proto/rpc_impl/service_registry.rs, easytier/src/proto/rpc_types/handler.rs
`easytier-cli stats`
It's useful to find out which components are consuming bandwidth.
=> add stats counters

easytier-web/frontend-lib/src/components/Config.vue, easytier-web/frontend-lib/src/locales/cn.yaml, easytier-web/frontend-lib/src/locales/en.yaml, easytier-web/frontend-lib/src/types/network.ts, easytier/src/launcher.rs, easytier/src/proto/web.proto
issue[#1196](https://github.com/EasyTier/EasyTier/issues/1196)
在gui界面和web界面中新增”端口转发“输入框
=> gui界面增加端口转发

easytier-gui/.gitignore, easytier-gui/flake.lock, easytier-gui/flake.nix
add android flake.nix 
增加本地构建安卓apk包环境
```
nix develop .#android --extra-experimental-features "nix-command flakes"
pnpm -r install
pnpm -r build
pnpm tauri android build
```
=> add a android flake.nix for local development/test/build

easytier-contrib/easytier-magisk/action.sh, easytier-contrib/easytier-magisk/customize.sh, easytier-contrib/easytier-magisk/easytier_core.sh, easytier-contrib/easytier-magisk/hotspot_iprule.sh, easytier-contrib/easytier-magisk/service.sh
增加magisk模块功能：热点局域网转发。
设置后台监控，热点打开，可自动增加转发规则。
在三星fold3测试通过。
=> 增加magisk模块功能：热点局域网转发。

easytier/src/gateway/tokio_smoltcp/socket.rs
see https://github.com/spacemeowx2/tokio-smoltcp/issues/11
=> fix dead lock in tokio smoltcp

easytier-gui/src/composables/tray.ts, easytier-gui/src/pages/index.vue
=> tray: place the exit menu item at bottom

easytier/src/tunnel/quic.rs
- **fix quic listen on dual stack**
- **fix quic accept fail**
=> fix quic transport

.github/workflows/ohos.yml, easytier-contrib/easytier-ohrs/.gitignore, easytier-contrib/easytier-ohrs/Cargo.lock, easytier-contrib/easytier-ohrs/Cargo.toml, easytier-contrib/easytier-ohrs/build.rs, easytier-contrib/easytier-ohrs/package/CHANGELOG.md, easytier-contrib/easytier-ohrs/package/LICENSE, easytier-contrib/easytier-ohrs/package/README.md, easytier-contrib/easytier-ohrs/package/index.ets, easytier-contrib/easytier-ohrs/package/oh-package.json5, easytier-contrib/easytier-ohrs/package/src/main/module.json5, easytier-contrib/easytier-ohrs/src/lib.rs, easytier-contrib/easytier-ohrs/src/native_log.rs
This GitHub Actions run looks good.  https://github.com/niuhuan/EasyTier/actions/runs/18168015296/job/51715349093
=> feat(ohos) build har package
